#!/usr/bin/env node

/**
 * Generate help text from README.md
 * 
 * This script reads README.md and generates src/generated/help.ts with the help text.
 * The README.md file is the single source of truth for documentation.
 * 
 * To update the CLI help text:
 * 1. Edit README.md
 * 2. Run `npm run generate-help` or just `npm run build` (which runs this automatically)
 * 
 * This script runs automatically before TypeScript compilation via the "prebuild" npm script.
 */

const fs = require('fs')
const path = require('path')

// Read README.md
const readmePath = path.join(__dirname, '..', 'README.md')
const readmeContent = fs.readFileSync(readmePath, 'utf8')

// Extract just the CLI help section (everything after "## Commands")
const commandsIndex = readmeContent.indexOf('## Commands')
if (commandsIndex === -1) {
  throw new Error('Could not find "## Commands" section in README.md')
}

// Take everything from "Commands" to the end, but stop at "## Development"
const developmentIndex = readmeContent.indexOf('## Development')
const helpContent = developmentIndex !== -1 
  ? readmeContent.slice(commandsIndex, developmentIndex).trim()
  : readmeContent.slice(commandsIndex).trim()

// Convert markdown to plain text for CLI help
const plainTextHelp = helpContent
  // Remove markdown headers
  .replace(/^#+\s+/gm, '')
  // Remove code block markers
  .replace(/```\w*\n/g, '')
  .replace(/```/g, '')
  // Convert markdown code spans to plain text
  .replace(/`([^`]+)`/g, '$1')
  // Clean up extra whitespace
  .replace(/\n\n\n+/g, '\n\n')
  .trim()

// Generate TypeScript file
const tsContent = `// This file is auto-generated from README.md by scripts/generate-help.js
// Do not edit this file directly - edit README.md instead

export const helpText = \`${plainTextHelp}\`
`

// Write the generated TypeScript file
const outputPath = path.join(__dirname, '..', 'src', 'generated', 'help.ts')
const outputDir = path.dirname(outputPath)

// Ensure the generated directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true })
}

fs.writeFileSync(outputPath, tsContent)

console.log('✅ Generated help text from README.md') 